import { defineArrayMember, defineField, defineType } from 'sanity';
import { imageField } from '../lib/imageField';

export const businessIdentity = defineType({
  name: 'businessIdentity',
  title: 'Business Identity',
  type: 'object',
  fieldsets: [
    { name: 'identity', title: 'Identity', options: { collapsible: true, collapsed: false } },
    { name: 'contact', title: 'Contact', options: { collapsible: true, collapsed: false } },
    { name: 'location', title: 'Location', options: { collapsible: true, collapsed: false } },
    { name: 'operations', title: 'Operations', options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Business Name',
      type: 'string',
      description: 'Public business name used for LocalBusiness/Bakery JSON-LD.',
      fieldset: 'identity',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'alternateName',
      title: 'Alternate Name',
      type: 'string',
      description: 'Optional alternate public name, abbreviation, or DBA if one is actively used.',
      fieldset: 'identity',
    }),
    defineField({
      name: 'legalName',
      title: 'Legal Name',
      type: 'string',
      description: 'Optional legal entity name. Leave blank if it should not be published.',
      fieldset: 'identity',
    }),
    defineField({
      name: 'description',
      title: 'Business Description',
      type: 'text',
      rows: 3,
      description: 'Short factual business description for LocalBusiness/Bakery JSON-LD. Do not use unverified claims.',
      fieldset: 'identity',
    }),
    defineField({
      name: 'url',
      title: 'Website URL',
      type: 'url',
      description: 'Canonical homepage URL for the business.',
      fieldset: 'identity',
      validation: (Rule) => Rule.required(),
    }),
    imageField('logo', 'Logo', {
      required: true,
      description: 'Official business logo used in Organization/Bakery JSON-LD.',
      fieldset: 'identity',
    }),
    imageField('image', 'Business Photo', {
      description: 'Optional representative business image for LocalBusiness/Bakery JSON-LD.',
      fieldset: 'identity',
    }),
    defineField({
      name: 'telephone',
      title: 'Telephone',
      type: 'string',
      description: 'Public business phone number in the exact format the business wants indexed.',
      fieldset: 'contact',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      description: 'Public business email address. Leave blank if email should not be indexed.',
      fieldset: 'contact',
    }),
    defineField({
      name: 'priceRange',
      title: 'Price Range',
      type: 'string',
      description: 'Optional local-business price range, e.g. $, $$, or a concise factual range.',
      fieldset: 'operations',
    }),
    defineField({
      name: 'sameAs',
      title: 'Same As URLs',
      type: 'array',
      of: [defineArrayMember({ type: 'url' })],
      description: 'Official social, review, or profile URLs that identify this business.',
      fieldset: 'identity',
    }),
    defineField({
      name: 'address',
      title: 'Address',
      type: 'object',
      description: 'Physical public business address. Leave blank if there is no customer-facing address.',
      fieldset: 'location',
      fields: [
        defineField({ name: 'streetAddress', title: 'Street Address', type: 'string', description: 'Street address exactly as it should appear in structured data.' }),
        defineField({ name: 'addressLocality', title: 'City', type: 'string', description: 'City or locality.' }),
        defineField({ name: 'addressRegion', title: 'State/Region', type: 'string', description: 'State or region abbreviation/name, e.g. NY.' }),
        defineField({ name: 'postalCode', title: 'Postal Code', type: 'string', description: 'Postal or ZIP code.' }),
        defineField({ name: 'addressCountry', title: 'Country', type: 'string', initialValue: 'US', description: 'Country code or country name, e.g. US.' }),
      ],
    }),
    defineField({
      name: 'geo',
      title: 'Geo Coordinates',
      type: 'object',
      description: 'Optional exact latitude/longitude for the public business location.',
      fieldset: 'location',
      fields: [
        defineField({ name: 'latitude', title: 'Latitude', type: 'number', validation: (Rule) => Rule.min(-90).max(90) }),
        defineField({ name: 'longitude', title: 'Longitude', type: 'number', validation: (Rule) => Rule.min(-180).max(180) }),
      ],
    }),
    defineField({
      name: 'hasMap',
      title: 'Map URL',
      type: 'url',
      description: 'Optional public map URL for the business location.',
      fieldset: 'location',
    }),
    defineField({
      name: 'serviceArea',
      title: 'Service Area',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      description: 'Cities, regions, or delivery areas served. Leave blank if not verified.',
      fieldset: 'operations',
    }),
    defineField({
      name: 'openingHours',
      title: 'Opening Hours',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      description: 'Schema.org openingHours strings, e.g. Mo-Fr 09:00-17:00. Leave blank if not verified.',
      fieldset: 'operations',
    }),
    defineField({
      name: 'paymentAccepted',
      title: 'Payment Accepted',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      description: 'Optional accepted payment methods, e.g. Cash, Credit Card, Apple Pay. Leave blank if not published.',
      fieldset: 'operations',
    }),
    defineField({
      name: 'currenciesAccepted',
      title: 'Currencies Accepted',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      description: 'Optional accepted currency codes, e.g. USD.',
      fieldset: 'operations',
    }),
  ],
});
